@startuml

title __CLI's Class Diagram__\n

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.AddCardCommand {
            ~ quitCommand : QuitCommand
            ~ reservationBuilder : ReservationBuilder
            ~ reservationRepo : ReservationRepo
            + execute()
            + setReservationBuilder()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.CancelCommand {
            ~ sc : Scanner
            - reservationService : ReservationService
            + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.CheckInCommand {
            ~ reservationRepo : ReservationRepo
            ~ reservationService : ReservationService
            ~ roomService : RoomService
            ~ sc : Scanner
            + execute()
            - chooseRoomForCheckIn()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.CheckOutCommand {
            - checkOutService : CheckOutService
            - sc : Scanner
            + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.ChoiceCommand {
            - cancelCommand : CancelCommand
            - checkInCommand : CheckInCommand
            - checkOutCommand : CheckOutCommand
            - findCommand : FindCommand
            - sc : Scanner
            + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        interface dss.hotelproject.cli.Command {
            {abstract} + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.CreateGuestCommand {
            - guestRepo : GuestRepo
            + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.FindCommand {
            - choiceCommand : ChoiceCommand
            - hotelRepo : HotelRepo
            - reservCommand : ReservCommand
            - reservationService : ReservationService
            - sc : Scanner
            + execute()
            - checkDateInput()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.QuitCommand {
            - choiceCommand : ChoiceCommand
            - sc : Scanner
            + execute()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace cli {
        class dss.hotelproject.cli.ReservCommand {
            ~ hotelRepo : HotelRepo
            ~ sc : Scanner
            - addCardCommand : AddCardCommand
            - createGuestCommand : CreateGuestCommand
            - firstDay : LocalDate
            - guestRepo : GuestRepo
            - hotel : Hotel
            - lastDay : LocalDate
            - roomType : RoomType
            - roomTypeByMaxNumOfPerson : RoomTypeByMaxNumOfPerson
            + execute()
            + setFirstDay()
            + setHotel()
            + setLastDay()
            + setRoomType()
            + setRoomTypeByMaxNumOfPerson()
            - getTotalCost()
        }
      }
    }
  }
  

  dss.hotelproject.cli.AddCardCommand .up.|> Command
  dss.hotelproject.cli.CancelCommand .up.|> Command
  dss.hotelproject.cli.CheckInCommand .up.|> Command
  dss.hotelproject.cli.CheckOutCommand .up.|> Command
  dss.hotelproject.cli.ChoiceCommand .up.|> Command
  dss.hotelproject.cli.CreateGuestCommand .up.|> Command
  dss.hotelproject.cli.FindCommand .up.|> Command
  dss.hotelproject.cli.QuitCommand .up.|> Command
  dss.hotelproject.cli.ReservCommand .up.|> Command


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
