@startuml

title __SERVICE's Class Diagram__\n

  namespace  {
    namespace ss.hotelproject {
      namespace Service {
        class dss.hotelproject.Service.CheckOutService {
            ~ paymentService : PaymentService
            ~ reservationRepo : ReservationRepo
            ~ roomRepo : RoomRepo
            + calculateAdditionalPayment()
            + checkOut()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace Service {
        class dss.hotelproject.Service.HotelService {
            ~ hotelRepo : HotelRepo
            + ifHotelExists()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace Service {
        class dss.hotelproject.Service.PaymentService {
            + pay()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace Service {
        class dss.hotelproject.Service.ReservationService {
            ~ hotelRepo : HotelRepo
            ~ paymentService : PaymentService
            ~ reservationRepo : ReservationRepo
            ~ roomRepo : RoomRepo
            + cancelReservation()
            + changePaymentMethod()
            + checkIn()
            + getReservationsWithinDates()
            - calculateCancellationCharge()
        }
      }
    }
  }
  

  namespace  {
    namespace ss.hotelproject {
      namespace Service {
        class dss.hotelproject.Service.RoomService {
            - roomRepo : RoomRepo
            + findFreeTypeRoomsForPeriod()
            + getAllRoomInHotelForNumberOfGuests()
            + getFreeRoomsForCheckIn()
        }
      }
    }
  }
  

  dss.hotelproject.Service.CheckOutService .up.|> ICheckOut
  dss.hotelproject.Service.HotelService .up.|> IHotelService
  dss.hotelproject.Service.PaymentService .up.|> IPay
  dss.hotelproject.Service.ReservationService .up.|> ICancellationService
  dss.hotelproject.Service.ReservationService .up.|> ICheckInService
  dss.hotelproject.Service.ReservationService .up.|> IReservationManage
  dss.hotelproject.Service.ReservationService .up.|> IReservationService
  dss.hotelproject.Service.RoomService .up.|> ISearchForFreeRooms


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
