@startuml

title __ENUM's Class Diagram__\n

  namespace  {
    namespace om.uca.dss20192020.hotelprojectclientwebservice {
      namespace Enum {
        enum RoomStatus {
          FREE
          OCCUPIED
          RESERVED
        }
      }
    }
  }
  

  namespace  {
    namespace om.uca.dss20192020.hotelprojectclientwebservice {
      namespace Enum {
        enum RoomType {
          BUSINESS
          STANDARD
          SUPERIOR
          priceByType
        }
      }
    }
  }
  

  namespace  {
    namespace om.uca.dss20192020.hotelprojectclientwebservice {
      namespace Enum {
        enum RoomTypeByMaxNumOfPerson {
          DOUBLE
          FAMILY
          SINGLE
          persons
        }
      }
    }
  }
  

  namespace  {
    namespace om.uca.dss20192020.hotelprojectclientwebservice {
      namespace Enum {
        enum Services {
          Breakfast
          Laundry
          Parking
          servicePrice
        }
      }
    }
  }
  

  namespace  {
    namespace om.uca.dss20192020.hotelprojectclientwebservice {
      namespace Enum {
        enum UserRoles {
          ADMIN
          CLIENT
        }
      }
    }
  }
  

  com.uca.dss20192020.hotelprojectclientwebservice.Enum.RoomStatus .up.|> java.io.Serializable
  com.uca.dss20192020.hotelprojectclientwebservice.Enum.RoomType .up.|> java.io.Serializable
  com.uca.dss20192020.hotelprojectclientwebservice.Enum.RoomTypeByMaxNumOfPerson .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
